Задание 5 - Доработка с докером
booogiman/shareIt pull request #4
Opened 2022-11-03 11:58 UTC by booogiman

2022-11-03 17:57 UTC, eugene-lenkevich requested changes
Привет, Лев, спасибо за PR

В целом все отлично, два сервиса, докер :)


Вся валидация на стороне гейтвея
 С одной стороны кажется немного странным такое требование, но в этом есть своя логика: не дублировать проверки ибо, в будущем, проверки придется править в разных местах и рано или поздно это приведет к рассинхронизации реализаций и появлению множества багов, как следствие. А в микросервисах починка багов - это то еще приключение :)

Иногда вообще как делают. Микросервис разбивают на два модуля: реализация и контракты (все dto и пр интерфейсы). Другой микросервис (в нашем случае это gateway), который хочет обратится к нашему сервису, импортирует наши контракты и с помощью них и строит запросы. Так обеспечивается соответствие API.
В контракты так же может быть помещен и web-клиент со всем настройками, соответственно, импортируем контракты, инжектим бин клиента, вызываем методы клиента, все остальное от нас сокрыто, не надо возится с настройками и API, в теории, всегда у нас соответствует :)

====

Что касается замечаний. 
Что то тесты не проходят, посмотри, пожалуйста

![image](https://user-images.githubusercontent.com/94845100/199798349-e581649f-096a-4623-99ec-0c5044ec4040.png)

Я могу предложить вот что. Тестовая дата захардкожена, если поменять на такую, вроде все работает, подойдет ли такое решение? :)

![image](https://user-images.githubusercontent.com/94845100/199798729-bf8ee7dd-4a51-49b4-8c15-fbc55f006ad2.png)

2022-11-03 17:57 UTC, eugene-lenkevich commented on shareit-server/src/main/java/ru/practicum/booking/BookingRepository.java
> +            "order by b.start desc")
В качестве параметров передается Pageable, в нем естьт сортировка, руками сортировку лучше не указывать, аналогично и для методов ниже :)

2022-11-03 19:00 UTC, booogiman commented on shareit-server/src/main/java/ru/practicum/booking/BookingRepository.java
> +            "order by b.start desc")
Да, дата захардкожена . не поменял. Думал поменять на now, но забыл)

2022-11-04 04:00 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-11-07 18:08 UTC, merged